---
#===========================================
#   Policies -> environment - Variables
#===========================================
Core:
  policies:
    power:
      - name: r143b-ucs
        power_redundancy: N+1
    thermal:
      - fan_control_mode: Balanced
        name: default
      - fan_control_mode: Balanced
        name: global-default
