version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)
  [![Developed by: Cisco](https://img.shields.io/badge/Developed%20by-Cisco-blue)](https://developer.cisco.com)

  # Easy IMM - Comprehensive example for Intersight

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with the value of [your-api-key]
  - Add variable secretkey with the value of [your-secret-file-content]

  ### Linux and Windows
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkeyfile="<secret-key-file-location>"
  ```

  ## Environment Variable for Deploy Process

  At this time the deploy process is separate from the profile creation process.  To accomplish deploy the script is using curl to deploy the profiles

  ### Linux
  ```bash
  export TF_VAR_secretkey=`cat <your-secretkey-file>`
  ```
  ## Auto-completion Notes:

  If you would like to enable Auto Completion in the Pools File for ip, mac, uuid, wwnn, and wwpn perform the following in Visual Studio Code.

  ### Install the YAML extension by Red Hat
  `Extensions`: Search for YAML and Select the 'YAML Language Support by Red Hat'

  ### Add the YAML Schema's below to the Visual Studio Code Settings

  `Settings` » `Settings`: Search for `YAML:Schemas`.

  Click: `Edit in settings.json`

  Configure the following in `yaml.schemas`
  ```bash
    "https://raw.githubusercontent.com/terraform-cisco-modules/easy-imm-comprehensive-example/main/schemas/pools.json": "pools.yaml"
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  
  ## NOTE:
  **When the Data is merged from the YAML files, it will run through the modules using for_each loop(s).  Sensitive Variables cannot be added to a for_each loop, instead use the variables below to add sensitive values for policies.**

  {{ .Inputs }}
  {{ .Outputs }}

  # Sub Modules

  If you want to see documentation on Variables for Submodules use the links below:

  ## Terraform Registry

  ### Policies

  [*Policies*](https://registry.terraform.io/modules/terraform-cisco-modules/policies/intersight/latest)

  ### Pools

  [*Pools*](https://registry.terraform.io/modules/terraform-cisco-modules/pools/intersight/latest)

  ### Profiles

  [*Domain*](https://registry.terraform.io/modules/terraform-cisco-modules/profiles-domain/intersight/latest)

  [*Chassis and Server*](https://registry.terraform.io/modules/terraform-cisco-modules/profiles/intersight/latest)

output:
  file: README.md
  mode: replace

sort:
  enabled: false

settings:
  read-comments: false